; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+03 on Wed Sep 15 2021 07:06:36 GMT+0200 (Central European Summer Time)
M280 P0 S90 ; retract BLTouch

