; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+03 on Wed Sep 15 2021 07:06:38 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

