; tfree1.g
; called when tool 1 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+03 on Wed Sep 15 2021 07:06:38 GMT+0200 (Central European Summer Time)

G60 S0
G91
G1 Z3 F6000
M83
G1 E-2 F6000
G1 E-6 F3000
G1 H1 U250 F7000